### ISSUE TITLE
Tasks of today

### ISSUE THREAD

**Issue by Clemens-Bretscher** [HansSprungfeld/cassava-classification-capstone#12]
- Paulos: update slides in Google Drive (split EDA from stakeholder slides and transfer to EDA slides)
- complete the EDA notebooks (docstrings, comments etc)
- evening: put together Repositories in one shared repository
- object detecion: google about different methods for object detection and classification
- YOLOR (clemens)
- pre-trained models (clemens)
- fast AI

**Comment by DagiPaulos** [comment]
completed

**Comment by DagiPaulos** [comment]
completed
