### ISSUE TITLE
EDA - part 1

### ISSUE THREAD

**Issue by Clemens-Bretscher** [HansSprungfeld/cassava-classification-capstone#3]
- Analyse the image data (dpi, RGB)
- count pixels of all photos (distribution, mean, etc.)
- Analyse RGB distributions
- Analyse the content (leaf, whole plant)
- Are there automatic image analysis tools (checking for focus) 
- Data cleaning: leave out photos with poor quality
- Some pictures are not leaves! some are the roots

**Comment by DagiPaulos** [comment]
completed
