### ISSUE TITLE
Base model

### ISSUE THREAD

**Issue by Clemens-Bretscher** [HansSprungfeld/cassava-classification-capstone#9]
- What can be used as a base model?
- for example: show the farmers 5 pictures of the disease and let them categorize the disease by themselves 
- analyze single leaf: how much green/brown surface area can be seen?
- (knowledge about the disease might inspire new ideas for base model...)

**Comment by DagiPaulos** [comment]
completed

**Comment by DagiPaulos** [comment]
completed
